### ISSUE TITLE
Package needs updating, yet again…

### ISSUE THREAD

**Issue by drogga3** [nioncode/Chocolatey-WDK10#4]
https://chocolatey.org/packages/windowsdriverkit10#comment-4201628042

**Comment by nioncode** [comment]
Thanks for the reminder.

The new WDK now requires Visual Studio 2019 and does not support VS 2017 anymore. Additionally, the install instructions say that you have to manually change the SDK installation of VS 2019, because it is not compatible by default with the WDK (https://docs.microsoft.com/en-us/windows-hardware/drivers/download-the-wdk):
> However, the version of the SDK that is compatible with the WDK for Windows 10, version 1903 is not currently the default SDK.

I don't know if this is still the case and did not have time to verify this, yet.

Aside from always running the latest version, Is there any reason to switch to the new WDK version?

**Comment by drogga3** [comment]
Desktop development for C++ in VS 2019 automatically selects the correct Windows 10 SDK version (10.0.18362.0) now and yes, I did verify, it is compatible. Perhaps they haven't really fixed the documents.

**Comment by aminya** [comment]
> Aside from always running the latest version, Is there any reason to switch to the new WDK version?

New WDK includes spectre lib which is necessary for many projects.

**Comment by nioncode** [comment]
Should be fixed after merging #5. I'll publish the update on the chocolatey repos asap.
